version: '3.8'

services:
  bookstack-sync:
    build: .
    container_name: bookstack-sync
    restart: always
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=prod
      - BOOKSTACK_SOURCE_BASEURL=${SOURCE_BOOKSTACK_URL}
      - BOOKSTACK_SOURCE_TOKENID=${SOURCE_BOOKSTACK_TOKEN_ID}
      - BOOKSTACK_SOURCE_TOKENSECRET=${SOURCE_BOOKSTACK_TOKEN_SECRET}
      - BOOKSTACK_DESTINATION_BASEURL=${DEST_BOOKSTACK_URL}
      - BOOKSTACK_DESTINATION_TOKENID=${DEST_BOOKSTACK_TOKEN_ID}
      - BOOKSTACK_DESTINATION_TOKENSECRET=${DEST_BOOKSTACK_TOKEN_SECRET}
    volumes:
      - ./logs:/app/logs
    healthcheck:
      test: ["CMD", "wget", "--spider", "-q", "http://localhost:8080/actuator/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - app-network

networks:
  app-network:
    driver: bridge